language: go
go:
    - 1.11.x
env:
    global:
        - GOOS=linux
        - GOARCH=arm
jobs:
  include:
    - stage: test
      script: go test -v ./...
    - stage: build
      script: cd cmd/protoclient && go build
    - script: cd cmd/server && go build
notifications:
    on_success: never
    on_failure: never
